### ISSUE TITLE
第15章 运用LSTM进行单变量时序预测时遇到如下警告

### ISSUE THREAD

**Issue by MrBigmonster** [hzy46/Deep-Learning-21-Examples#10]
如图，警告为
WARNING:tensorflow:Skipping summary for mean, must be a float, np.float32, np.int64, np.int32 or int or a serialized string of Summary.
WARNING:tensorflow:Skipping summary for observed, must be a float, np.float32, np.int64, np.int32 or int or a serialized string of Summary.
WARNING:tensorflow:Skipping summary for start_tuple, must be a float, np.float32, np.int64, np.int32 or int or a serialized string of Summary.
WARNING:tensorflow:Skipping summary for times, must be a float, np.float32, np.int64, np.int32 or int or a serialized string of Summary.
WARNING:tensorflow:Input graph does not use tf.data.Dataset or contain a QueueRunner. That means predict yields forever. This is probably a mistake.
请问如何解决？

**Comment by hzy46** [comment]
TensorFlow版本以及运行的是哪一个脚本？输出正常嘛？

**Comment by MrBigmonster** [comment]
TensorFlow=1.5.0，运行的是train_lstm.py，输出趋势看起来是对的，但不知道对均方根误差上会不会造成不利的影响

**Comment by hzy46** [comment]
这个是添加TensorBoard的summary的警告，误差上应该没有影响的^_^

**Comment by MrBigmonster** [comment]
何老师，最后一条警告是怎么回事呢？
另外，在TensorFlow1.7的版本中，官方TFTS包里的LSTM例子有了些改动，是针对之前例子存在的准确性问题所做出的修复吗，有没有必要更新到最新版本
