### ISSUE TITLE
scipy.misc.toimage API新版已经被弃用

### ISSUE THREAD

**Issue by wangkechun** [hzy46/Deep-Learning-21-Examples#11]
这里 https://github.com/hzy46/Deep-Learning-21-Examples/blob/master/chapter_1/save_pic.py#L25 使用的 API 已经被弃用

> https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.toimage.html#scipy-misc-toimage
> toimage is deprecated! toimage is deprecated in SciPy 1.0.0, and will be removed in 1.2.0. Use Pillow’s Image.fromarray directly instead.

这样是可以的
```
from PIL import Image
Image.fromarray((image_array*256).astype(np.uint8)).save(filename)
```

**Comment by MichaelYangMaiZhe** [comment]
还要加上import numpy as np
