### ISSUE TITLE
我有买你的书，但大哥你的百度网盘进不去阿

### ISSUE THREAD

**Issue by zzxxcc7412** [hzy46/Deep-Learning-21-Examples#15]
“在数据目录chapter_8_data/中”

由于数据文件通常比较大，建议读者在用到时候再进行下载，下载地址为：https://pan.baidu.com/s/1i7pKvFf
，提取码：1kmf。

Thanks

**Comment by hzy46** [comment]
咋进不去，密码不对还是？

**Comment by zzxxcc7412** [comment]
我点进去它显示
"分析连接中有违规或违法内容，无法继续查看"

**Comment by hzy46** [comment]
再试试看？我刚刚试了一下是没有问题的。如果不行的话我再重新分享一个链接给你

**Comment by zzxxcc7412** [comment]
大哥我试过所有方法，还是不行。

**Comment by hzy46** [comment]
试试这个：https://pan.baidu.com/s/19zt_R25jmUOzqzDPZ25d4g
