### ISSUE TITLE
第三章 转化为tfrecord格式错误

### ISSUE THREAD

**Issue by lyxlty** [hzy46/Deep-Learning-21-Examples#18]
return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))
TypeError: 'rock' has type str, but expected one of: bytes
您好，书是不错，可我用的python3.6 ，改了几处后还是有错，跑不了

**Comment by lyxlty** [comment]
@hzy46

**Comment by lyxlty** [comment]
@hzy46 您好，请问下我是不是图片路径没放対？不太会改，能讲解一下吗，谢谢了

**Comment by LiXin-Ren** [comment]
可以试下在def _bytes_feature(value)里面加入下面这句话
value = tf.compat.as_bytes(value)

**Comment by LiXin-Ren** [comment]
https://blog.csdn.net/lisa_ren_123/article/details/80199256
这里面有说解决办法

**Comment by lyxlty** [comment]
@hzy46 @LiXin-Ren 感谢～
`

**Comment by lyxlty** [comment]
@hzy46 您好,我在服务器跑的,在slim文件夹下执行tensorboard --logdir satellite/train_dir 生成的链接为啥打不开?网上搜索了好久还是没解决

**Comment by hzy46** [comment]
打开您服务器的ip地址，默认是6006端口，例如10.x.x.x:6007

**Comment by hzy46** [comment]
如果不行的话是不是您的服务器有防火墙过滤了？

**Comment by lyxlty** [comment]
@hzy46  您好,还是不可以, 因为我在外网, 输入公司的外网地址 x.x.x:6006 还是打不开,防火墙过滤不太清楚

**Comment by lyxlty** [comment]
@hzy46 应该是我在外网的缘故,去公司应该可以打开,多谢了
