### ISSUE TITLE
21个项目玩转深度学习第5章 目标检测

### ISSUE THREAD

**Issue by longzeyilang** [hzy46/Deep-Learning-21-Examples#21]
根据该书的第5章的内容，对数据进行训练，我的电脑配置GTX 1080TI 12G+64 ubuntu16.04lts，在训练过程中，监测GPU使用情况，运行容量沾满，导致电脑关机。请问如何解决这个问题，我是新手，能不能说的详细点

**Comment by hzy46** [comment]
可以尝试一下这样的操作:
配置voc.config文件的时候，把 
keep_aspect_ratio_resizer {
        min_dimension: xxx
        max_dimension: xxx
      }
里面的min_dimension和max_dimension都减小为原来的一半，这样占用内存就会显著降低

**Comment by hzy46** [comment]
应该是内存的问题，显卡12
G肯定够了

**Comment by longzeyilang** [comment]
我的是16g内存条

**Comment by hzy46** [comment]
额，目前没有QQ群，你把那个数值都改成原来的1/10试试？如果还是不行的话，可能就不是内存的问题了，可能是程序有bug。另外问下您tensorflow的版本是多少？

**Comment by longzeyilang** [comment]
1.8

**Comment by longzeyilang** [comment]
应该是程序的bug

**Comment by longzeyilang** [comment]
真的怀疑，程序有没有运行过，按照你的版本，编译都是错误，

**Comment by hzy46** [comment]
@longzeyilang 程序我测试过不下三次，而且这个是Google Detection API的官方代码。我不太清楚是不是你平台的问题，可以重新在你的平台下编译TensorFlow，可以消除一些兼容性的问题。

**Comment by longzeyilang** [comment]
我用python2.7测试：os.path.join(data['folder'], image_subdirectory, data['filename']) 这句话报错下标应为整数，
用python3.6测试：运行中奔溃

**Comment by hzy46** [comment]
是不是你配置文件没配好？os.path.join只是一个系统函数，你可以把这里的data['folder'], image_subdirectory, data['filename']都打出来看下

**Comment by longzeyilang** [comment]
我的言语有些过激，但是在上面耽误几天功夫，能不着急嘛
