### ISSUE TITLE
第三章,卫星图片数据集的下载地址

### ISSUE THREAD

**Issue by zhangyanpin** [hzy46/Deep-Learning-21-Examples#22]
第三章的微信图片下载地址在哪?虽然书中有提供图片,但我想知道源地址,有谁能提供更多的图像训练集的下载地址,谢谢了

**Comment by hzy46** [comment]
图片是在谷歌地图上爬的

**Comment by zhangyanpin** [comment]
请问使用python写的爬虫程序吗,可以分享学习下吗?

**Comment by hzy46** [comment]
这个爬虫程序已经找不到了，但是爬google map的程序有很多，可以上网搜一下~
