### ISSUE TITLE
Chapter 9未提供数据集food_resized和anime_resized

### ISSUE THREAD

**Issue by yufand** [hzy46/Deep-Learning-21-Examples#24]
9.4节提到“在 chapter_ 9_ data/ 中提供了两个已经整理好的数据集，分别保存为food_ resized. zip 和 anime_ resized. zip ”
但这两个文件未找到。

**Comment by hzy46** [comment]
参考readme https://github.com/hzy46/Deep-Learning-21-Examples#%E5%90%84%E7%AB%A0data%E6%96%87%E4%BB%B6%E5%A4%B9%E4%B8%8B%E8%BD%BD%E5%9C%B0%E5%9D%80
