### ISSUE TITLE
第三章目前遇到的几个问题

### ISSUE THREAD

**Issue by GeneralJing** [hzy46/Deep-Learning-21-Examples#29]
在训练的时候遇到的问题，都已经通过百度或者Google解决了，但是在验证模型测试的时候，报错了：
ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[100,64,147,147]
这个问题应该是空间不够了，我的GPU是GTX960 2Gb，按说应该是可以的，不知道有遇到此问题的吗？
另外一个问题是在到处pb文件的时候，产生如下错误：
INFO:tensorflow:Scale of 0 disables regularizer.
百度没查到相应的解决方法。

**Comment by GeneralJing** [comment]
恩 把batch数目调小一点之后，第一个问题解决了，第二个问题在产生pb文件的时候只有一个info提示，并没有产生对应的pb文件，这个是怎么回事呢？

**Comment by hzy46** [comment]
你有生成pb文件么？
参考：https://github.com/hzy46/Deep-Learning-21-Examples/tree/master/chapter_3 中的3.3.8导出模型并对单张图片进行识别

**Comment by GeneralJing** [comment]
就是在导出pb文件的时候，出现了那个提示，本地没有产生pb文件

**Comment by GeneralJing** [comment]
export_inference_graph.py这个导出pb文件的时候出现了那个提示，就没有了，看这个文件里面也没看到哪个地方出问题退出了

**Comment by hzy46** [comment]
可以跟踪一下是哪一步的问题~

**Comment by GeneralJing** [comment]
嗯，已经找到问题了，谢谢。

**Comment by diaoyongxiang** [comment]
您好，我也遇到这个问题，请问您是怎么解决的呢？ 可发邮件 18895701809@163.com

**Comment by diaoyongxiang** [comment]
INFO:tensorflow:Scale of 0 disables regularizer.

**Comment by diaoyongxiang** [comment]
问题已解决
