### ISSUE TITLE
5.2.1 安装TensorFlow Object Detection API

### ISSUE THREAD

**Issue by LeeyMessi** [hzy46/Deep-Learning-21-Examples#31]
前3步都是正确的 ，到了第4步执行“python object_detection/builders/model_builder_test.py”时，出现了
TypeError:__new__() got an unexpected keyword argument 'serialized_options'

**Comment by hzy46** [comment]
protoc版本是最新版吗？

**Comment by LeeyMessi** [comment]
是最新版本 ，还有一个问题，您书上写的是下载protoc-.3.3.0-linux-x86_64.zip，而https://pythonprogramming.net/creating-tfrecord-files-tensorflow-object-detection-api-tutorial/?completed=/custom-objects-tracking-tensorflow-object-detection-api-tutorial/说的是下载“Download the python version”，protoc releases page的网页，这是两个东西，，linux版的和python版的 有什么区别呢？

**Comment by LeeyMessi** [comment]
我在jupyter中，运行object_detection_tutorial.ipynb文件 ，同样出现了TypeError:__new__() got an unexpected keyword argument 'serialized_options'，protoc用的是最新版的linux版本的，3.6.0，我用的系统是ubuntu16.04，
