### ISSUE TITLE
关于“词汇表”的问题。

### ISSUE THREAD

**Issue by baiyoulong** [hzy46/Deep-Learning-21-Examples#39]
你好，你十二章，如果我要训练自己的数据集，该怎样生成vocab文件呢！

**Comment by hzy46** [comment]
所有空格隔开的字符串算一个词汇，如果没有空格隔开就不算词汇。注意标点符号之间也要有空格，作为单独的词汇处理。

**Comment by baiyoulong** [comment]
现在我有自己的数据集，我该用什么工具生成我可以拿来训练的vocab文件呢！

**Comment by baiyoulong** [comment]
@hzy46 现在我有自己的数据集，我该用什么工具生成我可以拿来训练的vocab文件呢！

**Comment by hzy46** [comment]
用python写一个程序，按空格拆词，去重即可。
