### ISSUE TITLE
chapter-自动上色

### ISSUE THREAD

**Issue by QRICKDD** [hzy46/Deep-Learning-21-Examples#40]
首先感谢博主的书，问下博主有训练好的食物上色和动漫上色的模型嘛。
穷学生买不起gpu，cpu训练要好久好久，@。@。动漫的估计要十几天。。。
还留着模型的话给个百度链接可好。

**Comment by QRICKDD** [comment]
抱歉看错了。epcho=5。不用十几天，我看错了。。。但是还是要好久。。。

**Comment by hzy46** [comment]
其实可以少训练一些epoch，见好就收即可。tensorboard里面可以观察效果。
