### ISSUE TITLE
Failed to find faces.zip in this Examples.

### ISSUE THREAD

**Issue by boyob** [hzy46/Deep-Learning-21-Examples#43]
There is not a 'faces.zip'  which mentioned  in Chapter 8.3.2. How can I get it, please?

**Comment by hzy46** [comment]
百度网盘 https://pan.baidu.com/s/1i7pKvFf 提取码 1kmf

https://github.com/hzy46/Deep-Learning-21-Examples#%E5%90%84%E7%AB%A0data%E6%96%87%E4%BB%B6%E5%A4%B9%E4%B8%8B%E8%BD%BD%E5%9C%B0%E5%9D%80
