### ISSUE TITLE
第二章2.1.4节相关代码似乎有误

### ISSUE THREAD

**Issue by xiao-keeplearning** [hzy46/Deep-Learning-21-Examples#9]
` filenames = [os.path.join(data_dir, 'data_batch_%d.bin' % i)
               for i in **xrange**(1, 6)]`             #amend to range

**Comment by hzy46** [comment]
不太理解，哪里有问题？

**Comment by xiao-keeplearning** [comment]
是您的小错误，xrange 应该改成 range吧

**Comment by hzy46** [comment]
xrange和range都可以的噢😯
